/**
 * YouTube: the free path. Nearly every podcast episode on YouTube has
 * captions — either uploaded by the channel or auto-generated by YouTube —
 * so the transcript costs nothing and no audio is ever downloaded.
 *
 * YouTube does rate-limit and sometimes block requests from cloud servers, so
 * captions are fetched through a ladder of strategies:
 *
 *   1. The watch page's embedded player response (fastest, most complete).
 *   2. The Innertube player API with an Android client identity, which is
 *      often served when the web client is refused.
 *   3. Public Invidious / Piped mirrors.
 *
 * If all three fail the job pauses and the phone tries the mirrors itself
 * from its own (residential) connection — see web/src/captions.ts.
 */
import { decodeEntities } from './text.js'
import type { Segment } from './transcribe.js'

type Fetch = typeof fetch

export interface VideoMeta {
  videoId: string
  title: string
  channel?: string
  description?: string
  publishedAt?: string
  durationMs?: number
  thumbnailUrl?: string
  url: string
}

export interface CaptionTrack {
  url: string
  languageCode: string
  name?: string
  /** "asr" for YouTube's auto-generated captions. */
  kind?: string
}

const ID = '[A-Za-z0-9_-]{11}'

export function parseYouTubeUrl(input: string): { videoId: string } | null {
  const s = input.trim()
  if (new RegExp(`^${ID}$`).test(s)) return null // a bare id is too ambiguous to accept
  let url: URL
  try {
    url = new URL(s.includes('://') ? s : `https://${s}`)
  } catch {
    return null
  }
  const host = url.hostname.replace(/^(www|m|music)\./, '')
  if (host === 'youtu.be') {
    const m = url.pathname.match(new RegExp(`^/(${ID})(?:[/?#]|$)`))
    return m ? { videoId: m[1] } : null
  }
  if (host !== 'youtube.com' && host !== 'youtube-nocookie.com') return null
  const v = url.searchParams.get('v')
  if (v && new RegExp(`^${ID}$`).test(v)) return { videoId: v }
  const m = url.pathname.match(new RegExp(`^/(?:shorts|live|embed|v)/(${ID})(?:[/?#]|$)`))
  return m ? { videoId: m[1] } : null
}

export function isYouTubeUrl(input: string): boolean {
  return parseYouTubeUrl(input) !== null
}

const UA =
  'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1'

// ---------------------------------------------------------------------------
// Player response (watch page / Innertube)

/** Pull the ytInitialPlayerResponse JSON out of a watch page. */
export function extractPlayerResponse(html: string): Record<string, unknown> | undefined {
  const m = html.match(/ytInitialPlayerResponse\s*=\s*(\{[\s\S]+?\})\s*;\s*(?:var\s|<\/script>|\n)/)
  if (!m) return undefined
  try {
    return JSON.parse(m[1])
  } catch {
    // The lazy match may have cut short at a "};" inside a string; scan forward.
    const start = html.indexOf(m[1])
    for (let end = start + m[1].length; end < Math.min(html.length, start + 4_000_000); end++) {
      if (html[end] !== '}') continue
      try {
        return JSON.parse(html.slice(start, end + 1))
      } catch {
        /* keep going */
      }
    }
    return undefined
  }
}

export function metaFromPlayerResponse(pr: Record<string, unknown>, videoId: string): Partial<VideoMeta> {
  const vd = (pr.videoDetails ?? {}) as Record<string, unknown>
  const mf = ((pr.microformat as Record<string, unknown> | undefined)?.playerMicroformatRenderer ?? {}) as Record<string, unknown>
  const thumbs = ((vd.thumbnail as Record<string, unknown> | undefined)?.thumbnails ?? []) as { url: string; width?: number }[]
  const best = [...thumbs].sort((a, b) => (b.width ?? 0) - (a.width ?? 0))[0]
  return {
    videoId,
    title: typeof vd.title === 'string' ? vd.title : undefined,
    channel: typeof vd.author === 'string' ? vd.author : undefined,
    description: typeof vd.shortDescription === 'string' ? vd.shortDescription : undefined,
    durationMs: typeof vd.lengthSeconds === 'string' || typeof vd.lengthSeconds === 'number' ? Number(vd.lengthSeconds) * 1000 : undefined,
    publishedAt: typeof mf.publishDate === 'string' ? mf.publishDate : undefined,
    thumbnailUrl: best?.url,
    url: `https://www.youtube.com/watch?v=${videoId}`,
  }
}

export function tracksFromPlayerResponse(pr: Record<string, unknown>): CaptionTrack[] {
  const captions = pr.captions as Record<string, unknown> | undefined
  const renderer = captions?.playerCaptionsTracklistRenderer as Record<string, unknown> | undefined
  const tracks = (renderer?.captionTracks ?? []) as { baseUrl: string; languageCode: string; kind?: string; name?: { simpleText?: string; runs?: { text: string }[] } }[]
  return tracks
    .filter((t) => t.baseUrl)
    .map((t) => ({
      url: t.baseUrl,
      languageCode: t.languageCode,
      kind: t.kind,
      name: t.name?.simpleText ?? t.name?.runs?.map((r) => r.text).join(''),
    }))
}

/**
 * Human captions beat auto-generated ones; the requested language beats
 * others; English is the tie-breaker because most podcasts are in it.
 */
export function pickTrack(tracks: CaptionTrack[], preferred = 'en'): CaptionTrack | undefined {
  const score = (t: CaptionTrack) => {
    let s = 0
    if (t.kind !== 'asr') s += 4
    const lang = t.languageCode.toLowerCase()
    if (lang === preferred || lang.startsWith(`${preferred}-`)) s += 2
    else if (lang.startsWith('en')) s += 1
    return s
  }
  return [...tracks].sort((a, b) => score(b) - score(a))[0]
}

// ---------------------------------------------------------------------------
// Caption formats

/** YouTube's default timedtext XML: <text start="1.2" dur="3.4">Hello</text> */
export function parseTimedTextXml(xml: string): Segment[] {
  const out: Segment[] = []
  const re = /<text\s+([^>]*)>([\s\S]*?)<\/text>/g
  let m: RegExpExecArray | null
  while ((m = re.exec(xml))) {
    const attrs = m[1]
    const start = Number(attrs.match(/start="([\d.]+)"/)?.[1])
    const dur = Number(attrs.match(/dur="([\d.]+)"/)?.[1])
    const text = decodeEntities(decodeEntities(m[2]))
      .replace(/<[^>]+>/g, '')
      .replace(/\s+/g, ' ')
      .trim()
    if (!text || Number.isNaN(start)) continue
    out.push({ start, end: Number.isNaN(dur) ? undefined : start + dur, text })
  }
  return out
}

/** YouTube's json3 format: { events: [{ tStartMs, dDurationMs, segs: [{ utf8 }] }] } */
export function parseJson3(json: string): Segment[] {
  const data = JSON.parse(json) as { events?: { tStartMs?: number; dDurationMs?: number; segs?: { utf8?: string }[] }[] }
  const out: Segment[] = []
  for (const ev of data.events ?? []) {
    if (!ev.segs) continue
    const text = ev.segs
      .map((s) => s.utf8 ?? '')
      .join('')
      .replace(/\s+/g, ' ')
      .trim()
    if (!text || ev.tStartMs === undefined) continue
    const start = ev.tStartMs / 1000
    out.push({ start, end: ev.dDurationMs !== undefined ? start + ev.dDurationMs / 1000 : undefined, text })
  }
  return out
}

export function parseCaptionBody(body: string): Segment[] {
  const trimmed = body.trimStart()
  if (trimmed.startsWith('{')) return parseJson3(trimmed)
  if (trimmed.startsWith('<')) return parseTimedTextXml(trimmed)
  if (trimmed.startsWith('WEBVTT') || /-->/.test(trimmed)) {
    // Lazy import keeps transcribe.ts free of a cycle.
    return []
  }
  return []
}

// ---------------------------------------------------------------------------
// Fetching

export class YouTubeBlockedError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'YouTubeBlockedError'
  }
}

async function fetchWatchPage(videoId: string, fetchImpl: Fetch): Promise<Record<string, unknown> | undefined> {
  const res = await fetchImpl(`https://www.youtube.com/watch?v=${videoId}&hl=en&bpctr=9999999999&has_verified=1`, {
    headers: { 'user-agent': UA, 'accept-language': 'en-US,en;q=0.9', cookie: 'CONSENT=YES+cb; SOCS=CAI' },
    redirect: 'follow',
  })
  if (!res.ok) return undefined
  const html = await res.text()
  return extractPlayerResponse(html)
}

async function fetchInnertube(videoId: string, fetchImpl: Fetch): Promise<Record<string, unknown> | undefined> {
  const res = await fetchImpl('https://www.youtube.com/youtubei/v1/player?prettyPrint=false', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'user-agent': 'com.google.android.youtube/19.09.37 (Linux; U; Android 11) gzip',
      'x-youtube-client-name': '3',
      'x-youtube-client-version': '19.09.37',
    },
    body: JSON.stringify({
      videoId,
      contentCheckOk: true,
      racyCheckOk: true,
      context: { client: { clientName: 'ANDROID', clientVersion: '19.09.37', androidSdkVersion: 30, hl: 'en', gl: 'US' } },
    }),
  })
  if (!res.ok) return undefined
  return (await res.json()) as Record<string, unknown>
}

function playable(pr: Record<string, unknown>): boolean {
  const status = (pr.playabilityStatus as Record<string, unknown> | undefined)?.status
  return status === undefined || status === 'OK' || status === 'CONTENT_CHECK_REQUIRED'
}

async function fetchTrackSegments(track: CaptionTrack, fetchImpl: Fetch): Promise<Segment[]> {
  const url = new URL(track.url)
  url.searchParams.set('fmt', 'json3')
  const res = await fetchImpl(url.toString(), { headers: { 'user-agent': UA } })
  if (!res.ok) throw new YouTubeBlockedError(`Caption download returned ${res.status}`)
  const body = await res.text()
  const segments = parseCaptionBody(body)
  if (segments.length === 0) throw new YouTubeBlockedError('Caption download came back empty')
  return segments
}

/** Default public mirrors; override with YOUTUBE_MIRRORS (comma-separated origins). */
export const DEFAULT_MIRRORS = ['https://inv.nadeko.net', 'https://yewtu.be', 'https://invidious.nerdvpn.de', 'https://pipedapi.kavin.rocks']

async function fetchViaMirror(origin: string, videoId: string, fetchImpl: Fetch, preferred: string): Promise<{ segments: Segment[]; meta?: Partial<VideoMeta> } | undefined> {
  const isPiped = /piped/i.test(origin)
  if (isPiped) {
    const res = await fetchImpl(`${origin}/streams/${videoId}`, { headers: { 'user-agent': UA } })
    if (!res.ok) throw new Error(`mirror returned ${res.status}`)
    const data = (await res.json()) as { title?: string; uploader?: string; duration?: number; uploadDate?: string; description?: string; thumbnailUrl?: string; subtitles?: { url: string; code: string; autoGenerated?: boolean; name?: string }[] }
    const track = pickTrack((data.subtitles ?? []).map((s) => ({ url: s.url, languageCode: s.code, kind: s.autoGenerated ? 'asr' : undefined, name: s.name })), preferred)
    if (!track) return undefined
    const body = await (await fetchImpl(track.url)).text()
    const { parseSrtOrVtt } = await import('./transcribe.js')
    const segments = body.trimStart().startsWith('WEBVTT') || body.includes('-->') ? parseSrtOrVtt(body) : parseCaptionBody(body)
    return {
      segments,
      meta: { title: data.title, channel: data.uploader, durationMs: data.duration ? data.duration * 1000 : undefined, publishedAt: data.uploadDate, description: data.description, thumbnailUrl: data.thumbnailUrl },
    }
  }
  const res = await fetchImpl(`${origin}/api/v1/captions/${videoId}`, { headers: { 'user-agent': UA } })
  if (!res.ok) throw new Error(`mirror returned ${res.status}`)
  const data = (await res.json()) as { captions?: { label: string; language_code: string; url: string }[] }
  const track = pickTrack((data.captions ?? []).map((c) => ({ url: `${origin}${c.url}`, languageCode: c.language_code, kind: /auto-generated/i.test(c.label) ? 'asr' : undefined, name: c.label })), preferred)
  if (!track) return undefined
  const body = await (await fetchImpl(track.url)).text()
  const { parseSrtOrVtt } = await import('./transcribe.js')
  return { segments: parseSrtOrVtt(body) }
}

export async function fetchOEmbed(videoId: string, fetchImpl: Fetch): Promise<Partial<VideoMeta> | undefined> {
  try {
    const res = await fetchImpl(`https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`, { headers: { 'user-agent': UA } })
    if (!res.ok) return undefined
    const data = (await res.json()) as { title?: string; author_name?: string; thumbnail_url?: string }
    return { title: data.title, channel: data.author_name, thumbnailUrl: data.thumbnail_url }
  } catch {
    return undefined
  }
}

export interface YouTubeResult {
  meta: VideoMeta
  segments?: Segment[]
  /** How the captions were obtained, for the UI. */
  via?: 'watch' | 'innertube' | 'mirror'
  /** Set when captions could not be fetched from this server. */
  blocked?: string
}

/**
 * Everything we can get about a video from the server side. Always returns
 * metadata when any source responds; returns segments when captions could
 * be fetched, and otherwise a `blocked` reason so the client can take over.
 */
export async function fetchYouTube(videoId: string, opts: { fetch?: Fetch; mirrors?: string[]; language?: string } = {}): Promise<YouTubeResult> {
  const fetchImpl = opts.fetch ?? fetch
  const preferred = opts.language ?? 'en'
  let meta: Partial<VideoMeta> = { videoId, url: `https://www.youtube.com/watch?v=${videoId}` }
  const reasons: string[] = []
  // Only YouTube itself can tell us a video has no captions; a mirror that
  // has none may simply not have processed the video.
  let youtubeSaysNoCaptions = false

  const attempts: { via: YouTubeResult['via']; run: () => Promise<Record<string, unknown> | undefined> }[] = [
    { via: 'watch', run: () => fetchWatchPage(videoId, fetchImpl) },
    { via: 'innertube', run: () => fetchInnertube(videoId, fetchImpl) },
  ]
  for (const attempt of attempts) {
    try {
      const pr = await attempt.run()
      if (!pr) {
        reasons.push(`${attempt.via}: no response`)
        continue
      }
      meta = { ...meta, ...stripUndefined(metaFromPlayerResponse(pr, videoId)) }
      if (!playable(pr)) {
        const ps = pr.playabilityStatus as Record<string, unknown>
        reasons.push(`${attempt.via}: ${ps.status} ${ps.reason ?? ''}`.trim())
        continue
      }
      const track = pickTrack(tracksFromPlayerResponse(pr), preferred)
      if (!track) {
        youtubeSaysNoCaptions = true
        reasons.push(`${attempt.via}: video has no captions`)
        continue
      }
      const segments = await fetchTrackSegments(track, fetchImpl)
      return { meta: finalizeMeta(meta), segments, via: attempt.via }
    } catch (err) {
      reasons.push(`${attempt.via}: ${(err as Error).message}`)
    }
  }

  for (const origin of opts.mirrors ?? DEFAULT_MIRRORS) {
    try {
      const hit = await fetchViaMirror(origin, videoId, fetchImpl, preferred)
      if (hit?.segments.length) {
        meta = { ...stripUndefined(hit.meta ?? {}), ...stripUndefined(meta) }
        return { meta: finalizeMeta(meta), segments: hit.segments, via: 'mirror' }
      }
      reasons.push(`${origin}: no captions`)
    } catch (err) {
      reasons.push(`${origin}: ${(err as Error).message}`)
    }
  }

  if (!meta.title) meta = { ...meta, ...stripUndefined((await fetchOEmbed(videoId, fetchImpl)) ?? {}) }
  return {
    meta: finalizeMeta(meta),
    blocked: youtubeSaysNoCaptions
      ? 'This video has no captions on YouTube.'
      : `YouTube would not serve captions to this server (${reasons.slice(-2).join('; ')}).`,
  }
}

function stripUndefined<T extends object>(o: T): Partial<T> {
  return Object.fromEntries(Object.entries(o).filter(([, v]) => v !== undefined)) as Partial<T>
}

function finalizeMeta(meta: Partial<VideoMeta>): VideoMeta {
  return {
    videoId: meta.videoId!,
    url: meta.url ?? `https://www.youtube.com/watch?v=${meta.videoId}`,
    title: meta.title ?? `YouTube video ${meta.videoId}`,
    channel: meta.channel,
    description: meta.description,
    publishedAt: meta.publishedAt,
    durationMs: meta.durationMs,
    thumbnailUrl: meta.thumbnailUrl,
  }
}
