/**
 * When YouTube refuses the server (cloud IPs get rate-limited), the phone
 * fetches the captions itself through public YouTube mirrors whose APIs allow
 * browser requests, and hands the text to the server. Your home connection is
 * exactly the kind of request YouTube is happy to serve.
 */

export const MIRRORS = ['https://inv.nadeko.net', 'https://yewtu.be', 'https://invidious.nerdvpn.de', 'https://pipedapi.kavin.rocks']

async function withTimeout<T>(p: Promise<T>, ms: number): Promise<T> {
  return await Promise.race([p, new Promise<T>((_, reject) => setTimeout(() => reject(new Error('timed out')), ms))])
}

function pick<T extends { languageCode: string; auto: boolean }>(tracks: T[]): T | undefined {
  const score = (t: T) => (t.auto ? 0 : 4) + (t.languageCode.toLowerCase().startsWith('en') ? 2 : 0)
  return [...tracks].sort((a, b) => score(b) - score(a))[0]
}

async function fromInvidious(origin: string, videoId: string): Promise<string | undefined> {
  const res = await withTimeout(fetch(`${origin}/api/v1/captions/${videoId}`), 8000)
  if (!res.ok) return undefined
  const data = (await res.json()) as { captions?: { label: string; language_code: string; url: string }[] }
  const track = pick((data.captions ?? []).map((c) => ({ languageCode: c.language_code, auto: /auto-generated/i.test(c.label), url: `${origin}${c.url}` })))
  if (!track) return undefined
  const body = await withTimeout(fetch(track.url), 15000)
  return body.ok ? body.text() : undefined
}

async function fromPiped(origin: string, videoId: string): Promise<string | undefined> {
  const res = await withTimeout(fetch(`${origin}/streams/${videoId}`), 8000)
  if (!res.ok) return undefined
  const data = (await res.json()) as { subtitles?: { url: string; code: string; autoGenerated?: boolean }[] }
  const track = pick((data.subtitles ?? []).map((s) => ({ languageCode: s.code, auto: Boolean(s.autoGenerated), url: s.url })))
  if (!track) return undefined
  const body = await withTimeout(fetch(track.url), 15000)
  return body.ok ? body.text() : undefined
}

/**
 * Try each mirror in turn. Resolves with WebVTT text, or undefined when no
 * mirror could help. Never throws: this is a best effort before asking the
 * user to paste.
 */
export async function fetchCaptionsFromPhone(videoId: string, onProgress?: (msg: string) => void, mirrors = MIRRORS): Promise<string | undefined> {
  for (const origin of mirrors) {
    onProgress?.(`Trying ${new URL(origin).hostname}…`)
    try {
      const text = /piped/i.test(origin) ? await fromPiped(origin, videoId) : await fromInvidious(origin, videoId)
      if (text && text.split(/\s+/).length > 200) return text
    } catch {
      /* next mirror */
    }
  }
  return undefined
}
