/**
 * Hand-drawn head parts for the 16×32 overworld people, one stamp per facing.
 * Every stamp is 16 columns wide; the skull sits in columns 2–13, rows 2–11.
 *
 * Skin: s base, S shade, L light. Hair: H highlight, h base, d shade, D deep.
 * Headwear: A highlight, a base, b shade, B deep, x/X accent and its shade,
 * k dark band, w white. '.' is clear.
 */
import type { HairStyle, Headwear } from '../look'

export type View = 'down' | 'up' | 'left'

export const SKULL: Record<View, readonly string[]> = {
  down: [
    '................',
    '................',
    '.....ssssss.....',
    '...ssssssssss...',
    '..ssssssssssss..',
    '..ssssssssssss..',
    '..ssssssssssss..',
    '..sssssssssssS..',
    '..LssssssssssS..',
    '..LssssssssssS..',
    '...ssssssssSS...',
    '....SSSSSSSS....',
  ],
  up: [
    '................',
    '................',
    '.....ssssss.....',
    '...ssssssssss...',
    '..ssssssssssss..',
    '..ssssssssssss..',
    '..ssssssssssss..',
    '..ssssssssssss..',
    '..ssssssssssss..',
    '..LsssssssssSS..',
    '...sssssssssS...',
    '....SSSSSSSS....',
  ],
  left: [
    '................',
    '................',
    '.....ssssss.....',
    '...ssssssssss...',
    '..ssssssssssss..',
    '..ssssssssssss..',
    '..ssssssssssss..',
    '..sssssssssssS..',
    '..sssssssssssS..',
    '..LssssssssssS..',
    '...sssssssSSS...',
    '....SSSSSS......',
  ],
}

/** Eye pixels (x, y) per view, drawn after the hair so they always read. */
export const EYES: Record<View, readonly (readonly [number, number])[]> = {
  down: [
    [5, 7],
    [5, 8],
    [10, 7],
    [10, 8],
  ],
  up: [],
  left: [
    [4, 7],
    [4, 8],
  ],
}

type Stamps = Record<View, readonly string[]>

const CAP_DOWN = [
  '................',
  '................',
  '.....hhhhhh.....',
  '...hhhHHHhhhh...',
  '..hhhHHhhhhhhd..',
  '..hhhhhhhhhhhd..',
  '..hhhhhhhhhhhd..',
]
const CAP_UP = [
  '................',
  '................',
  '.....hhhhhh.....',
  '...hhhHHHhhhh...',
  '..hhhHHhhhhhhd..',
  '..hhhhhhhhhhhd..',
  '..hhhhhhhhhhhd..',
  '..hhhhhhhhhhhd..',
  '..dhhhhhhhhhdd..',
]
const CAP_LEFT = [
  '................',
  '................',
  '.....hhhhhh.....',
  '...hhhHHHhhhh...',
  '..hhhHHhhhhhhd..',
  '..hhhhhhhhhhhd..',
  '..hhhhhhhhhhhd..',
]

export const HAIR: Record<HairStyle, Stamps> = {
  short: {
    down: [...CAP_DOWN, '..hd..h.h...dd..', '..h..........d..'],
    up: [...CAP_UP, '...dhhhhhhhhd...', '....dddddddd....'],
    left: [...CAP_LEFT, '..hh.....hhhdd..', '.........hhhd...', '.........hhdd...', '..........dd....'],
  },
  spiky: {
    down: [
      '......h..h......',
      '...h..hhhh..h...',
      '...hhhhhhhhhh...',
      '..hhhHHHHhhhhh..',
      '.hhhHHhhhhhhhhd.',
      '..hhhhhhhhhhhdd.',
      '..hhdhhhdhhhhd..',
      '..hd.h...h.hdd..',
      '..h..........d..',
    ],
    up: [
      '......h..h......',
      '...h..hhhh..h...',
      '...hhhhhhhhhh...',
      '..hhhHHHHhhhhh..',
      '.hhhHHhhhhhhhhd.',
      '..hhhhhhhhhhhhd.',
      '.hhhhhhhhhhhhdd.',
      '..hhhhhhhhhhhd..',
      '.dhhhhhhhhhhhdd.',
      '...dhhhdhhhhd...',
      '....d.dd.dd.....',
    ],
    left: [
      '.......h..h.....',
      '....h..hhhhh.h..',
      '....hhhhhhhhhhh.',
      '...hhHHHHhhhhhhh',
      '..hhHHhhhhhhhhd.',
      '..hhhhhhhhhhhhdd',
      '..hhhhhhhhhhhdd.',
      '..hh.h...hhhhdd.',
      '.........hhhhdd.',
      '.........hhhdd..',
      '..........ddd...',
    ],
  },
  long: {
    down: [
      ...CAP_DOWN.slice(0, 6),
      '..hhhhhhhhhhhhd.',
      '.hhd.h....h.dhd.',
      '.hh..........dd.',
      '.hh..........dd.',
      '.hh..........dd.',
      '.hhd........ddd.',
      '.hhd........ddd.',
      '..hd........dd..',
    ],
    up: [
      ...CAP_UP.slice(0, 7),
      '.hhhhhhhhhhhhhd.',
      '.hhhhhhhhhhhhhd.',
      '.hhhhhhhhhhhhhd.',
      '.hhhhhhhhhhhhdd.',
      '.dhhhhhhhhhhhdd.',
      '.dhhhhhhhhhhhdd.',
      '..dhhhhhhhhhdd..',
      '...dddddddddd...',
    ],
    left: [
      ...CAP_LEFT,
      '..hh.....hhhhdd.',
      '.........hhhhdd.',
      '........hhhhhdd.',
      '........hhhhhdd.',
      '........hhhhhdd.',
      '.........hhhhdd.',
      '.........hhhdd..',
      '..........ddd...',
    ],
  },
  ponytail: {
    down: [...CAP_DOWN, '..hd..h.h...ddd.', '..h..........ddd', '..............dd', '..............d.'],
    up: [
      ...CAP_UP,
      '...dhhhhhhhhd...',
      '....ddhhhhdd....',
      '......hhhd......',
      '......hhhd......',
      '......hhdd......',
      '.......dd.......',
    ],
    left: [
      ...CAP_LEFT,
      '..hh.....hhhhddd',
      '.........hhhhhdd',
      '.........hhhd.dd',
      '..........dd..dd',
      '..............d.',
    ],
  },
  bun: {
    down: [
      '......HHhh......',
      '.....Hhhhhd.....',
      '.....hhhhhd.....',
      '...hhhHHHhhhh...',
      '..hhhHHhhhhhhd..',
      '..hhhhhhhhhhhd..',
      '..hhhhhhhhhhhd..',
      '..hd..h.h...dd..',
      '..h..........d..',
    ],
    up: [
      '......HHhh......',
      '.....Hhhhhd.....',
      '.....hhhhhd.....',
      '...hhhHHHhhhh...',
      '..hhhHHhhhhhhd..',
      '..hhhhhhhhhhhd..',
      '..hhhhhhhhhhhd..',
      '..hhhhhhhhhhhd..',
      '..dhhhhhhhhhdd..',
      '...dhhhhhhhhd...',
      '....dddddddd....',
    ],
    left: [
      '...........HHh..',
      '..........Hhhhd.',
      '.....hhhhhhhhhd.',
      '...hhhHHHhhhhdd.',
      '..hhhHHhhhhhhd..',
      '..hhhhhhhhhhhd..',
      '..hhhhhhhhhhhd..',
      '..hh.....hhhdd..',
      '.........hhhd...',
      '.........hhdd...',
      '..........dd....',
    ],
  },
  bob: {
    down: [
      ...CAP_DOWN.slice(0, 6),
      '..hhhhhhhhhhhhd.',
      '.hhh.h....h.hhd.',
      '.hh..........dd.',
      '.hh..........dd.',
      '.hhd........ddd.',
      '..dd........dd..',
    ],
    up: [...CAP_UP, '.hhhhhhhhhhhhhd.', '.hhhhhhhhhhhhhd.', '.dhhhhhhhhhhhdd.', '..dddddddddddd..'],
    left: [
      ...CAP_LEFT,
      '..hhh....hhhhdd.',
      '.........hhhhdd.',
      '........hhhhhdd.',
      '........hhhhdd..',
      '.........dddd...',
    ],
  },
  bald: {
    down: ['................', '................', '.....LL.........', '....L...........', '................', '................', '..h..........d..', '..h..........d..', '..d..........d..'],
    up: ['................', '................', '.....LL.........', '....L...........', '................', '................', '..h..........d..', '..hhdhhhhhdhhd..', '..dhhhhhhhhhhd..', '...dddddddddd...'],
    left: ['................', '................', '......LL........', '.....L..........', '................', '................', '..........hhd...', '.........hhhdd..', '.........hhhd...', '..........dd....'],
  },
  curly: {
    down: [
      '................',
      '....h.hhhh.h....',
      '...hhhhHhhhhh...',
      '..hhHhHhhhhHhh..',
      '.hhHhhhhHhhhhhd.',
      '.hhhhHhhhhhhHhd.',
      '.hhdhhhdhhdhhhd.',
      '.hhd.h....h.dhd.',
      '.hd..........dd.',
      '..d..........d..',
    ],
    up: [
      '................',
      '....h.hhhh.h....',
      '...hhhhHhhhhh...',
      '..hhHhHhhhhHhh..',
      '.hhHhhhhHhhhhhd.',
      '.hhhhHhhhhhhHhd.',
      '.hhhhhhhhhhhhhd.',
      '.hhdhhhHhhhdhhd.',
      '.hhhhdhhhhhhhdd.',
      '.dhdhhhhdhhdhdd.',
      '..ddhdddhddhdd..',
    ],
    left: [
      '................',
      '....h.hhhh.h....',
      '...hhhhHhhhhh...',
      '..hhHhHhhhhHhh..',
      '.hhHhhhhHhhhhhd.',
      '.hhhhHhhhhhhHhd.',
      '.hhdhhhdhhdhhhd.',
      '.hh......hhhhdd.',
      '.........hhdhdd.',
      '........hhhhhdd.',
      '.........dhddd..',
    ],
  },
  braids: {
    down: [
      ...CAP_DOWN,
      '.hhd..h.h...dhd.',
      '.hh..........dd.',
      '.hd..........dd.',
      '.dh..........hd.',
      '.hd..........dd.',
      '.dh..........hd.',
      '.hd..........dd.',
      '.xx..........xx.',
    ],
    up: [
      ...CAP_UP,
      '.hdhhhhhhhhhdhd.',
      '.hh.dddddddd.dd.',
      '.hd..........dd.',
      '.dh..........hd.',
      '.hd..........dd.',
      '.dh..........hd.',
      '.xx..........xx.',
    ],
    left: [
      ...CAP_LEFT,
      '..hh.....hhhhd..',
      '.........hhhdd..',
      '.........hdhd...',
      '..........dhd...',
      '..........hdh...',
      '..........dhd...',
      '..........hdh...',
      '..........xx....',
    ],
  },
  mohawk: {
    down: [
      '......hhh.......',
      '......Hhd.......',
      '......Hhd.......',
      '.....hHhhd......',
      '......hhd.......',
      '......hhd.......',
    ],
    up: ['......hhh.......', '......Hhd.......', '......Hhd.......', '.....hHhhd......', '......hhd.......', '......hhd.......', '......hhd.......', '......hdd.......', '.......d........'],
    left: [
      '.....hhhh.......',
      '....hHHhhhhh....',
      '.....hhhhhhhhd..',
      '.......hhhhhhhd.',
      '...........hhd..',
      '............d...',
    ],
  },
}

/** Rows above which hair is hidden when wearing each kind of headwear. */
export const HAT_LINE: Record<Headwear, number> = {
  none: 0,
  cap: 7,
  bandana: 6,
  sunhat: 7,
  beanie: 7,
  hardhat: 7,
  captain: 7,
  hood: 12,
}

export const HAT: Record<Exclude<Headwear, 'none'>, Stamps> = {
  cap: {
    down: [
      '................',
      '.......A........',
      '.....aaaaaa.....',
      '...aaAAAaaaab...',
      '..aaAAaaaaaabb..',
      '..aaaaaaaaaabb..',
      '..xxxxxxxxxxxX..',
    ],
    up: [
      '................',
      '.......A........',
      '.....aaaaaa.....',
      '...aaAAAaaaab...',
      '..aaAAaaaaaabb..',
      '..aaaaaaaaaabb..',
      '..aaaaaaaaaabb..',
      '..bbbbw..wbbbb..',
    ],
    left: [
      '................',
      '.........A......',
      '.....aaaaaaa....',
      '...aaAAAaaaab...',
      '..aaAAaaaaaabb..',
      '..aaaaaaaaaabb..',
      'xxxxxxaaaaaabb..',
      '.XXXXX..........',
    ],
  },
  bandana: {
    down: [
      '................',
      '................',
      '.....aaaaaa.....',
      '...aaAwAaaaab...',
      '..aaAAaaawaabb..',
      '..awaaaaaaaabbb.',
      '..bbbbbbbbbbbBbb',
      '..............b.',
    ],
    up: [
      '................',
      '................',
      '.....aaaaaa.....',
      '...aaAwAaaaab...',
      '..aaAAaaawaabb..',
      '..awaaaaaaaabb..',
      '..bbbbbaabbbbB..',
      '......abbb......',
      '.....ab..bb.....',
      '.....b....b.....',
    ],
    left: [
      '................',
      '................',
      '.....aaaaaa.....',
      '...aaAwAaaaab...',
      '..aaAAaaawaabb..',
      '..awaaaaaaaabbb.',
      '..bbbbbbbbbbbabb',
      '.............bb.',
      '..............b.',
    ],
  },
  sunhat: {
    down: [
      '................',
      '.....aAAaaa.....',
      '....aAaaaaab....',
      '....aaaaaaab....',
      '....xxxxxxxX....',
      '.aaaaaaaaaaaaab.',
      '..bbbbbbbbbbbb..',
    ],
    up: [
      '................',
      '.....aAAaaa.....',
      '....aAaaaaab....',
      '....aaaaaaab....',
      '....xxxxxxxX....',
      '.aaaaaaaaaaaaab.',
      '.aaaaaaaaaaaabb.',
      '..bbbbbbbbbbbb..',
    ],
    left: [
      '................',
      '.....aAAaaa.....',
      '....aAaaaaab....',
      '....aaaaaaab....',
      '....xxxxxxxX....',
      'aaaaaaaaaaaaaaab',
      '.bbbbbbbbbbbbbb.',
    ],
  },
  beanie: {
    down: [
      '.......Ax.......',
      '.......xX.......',
      '.....aaaaaa.....',
      '...aaAAaaaaab...',
      '..aaAaaaaaaabb..',
      '..AaAaAaAaAabB..',
      '..ababababababB.',
    ],
    up: [
      '.......Ax.......',
      '.......xX.......',
      '.....aaaaaa.....',
      '...aaAAaaaaab...',
      '..aaAaaaaaaabb..',
      '..aaaaaaaaaabb..',
      '..AaAaAaAaAabB..',
      '..ababababababB.',
    ],
    left: [
      '........Ax......',
      '........xX......',
      '.....aaaaaa.....',
      '...aaAAaaaaab...',
      '..aaAaaaaaaabb..',
      '..AaAaAaAaAabB..',
      '..ababababababB.',
    ],
  },
  hardhat: {
    down: [
      '................',
      '......aaaa......',
      '....aAAaaaab....',
      '...aAAaaaaabb...',
      '..aAaaaAaaaabb..',
      '..aaaaaAaaaabb..',
      '.bbbbbbbbbbbbbB.',
    ],
    up: [
      '................',
      '......aaaa......',
      '....aAAaaaab....',
      '...aAAaaaaabb...',
      '..aAaaaAaaaabb..',
      '..aaaaaAaaaabb..',
      '..aaaaaAaaaabb..',
      '.bbbbbbbbbbbbbB.',
    ],
    left: [
      '................',
      '......aaaa......',
      '....aAAaaaab....',
      '...aAAaaaaabb...',
      '..aAaaaaaaaabb..',
      '..aaAAAAAAAAbb..',
      'bbbbbbbbbbbbbbB.',
    ],
  },
  captain: {
    down: [
      '....wwwwwwww....',
      '...wwwwwwwwwwW..',
      '...wwwwwwwwwwW..',
      '....WWWWWWWW....',
      '...kkkkxxkkkk...',
      '..kkkkkXXkkkkk..',
      '..BBBBBBBBBBBB..',
    ],
    up: [
      '....wwwwwwww....',
      '...wwwwwwwwwwW..',
      '...wwwwwwwwwwW..',
      '...wwwwwwwwwwW..',
      '....WWWWWWWW....',
      '...kkkkkkkkkk...',
      '..kkkkkkkkkkkk..',
    ],
    left: [
      '...wwwwwwww.....',
      '..wwwwwwwwwwW...',
      '..wwwwwwwwwwW...',
      '...WWWWWWWWW....',
      '..xkkkkkkkkkk...',
      '..kkkkkkkkkkkk..',
      'BBBBB...........',
    ],
  },
  hood: {
    down: [
      '................',
      '.....aaaaaa.....',
      '...aaAAAaaaab...',
      '..aaAAaaaaaabb..',
      '..aAaaaaaaaabb..',
      '..aaabbbbbbabb..',
      '..aab......bbb..',
      '..aa........bb..',
      '..aa........bb..',
      '..aa........bb..',
      '..aab......bbb..',
      '..aaab....bbbb..',
      '.aaaaaaaaaaabbb.',
    ],
    up: [
      '................',
      '.....aaaaaa.....',
      '...aaAAAaaaab...',
      '..aaAAaaaaaabb..',
      '..aAaaaaaaaabb..',
      '..aaaaaaaaaabb..',
      '..aaaaaaaaaabb..',
      '..aaaaaaaaaabb..',
      '..aaaaaaaaaabb..',
      '..aaaaaaaaabbb..',
      '..aaaaaaaabbbb..',
      '..baaaaaabbbbb..',
      '.bbbbbbbbbbbbbb.',
    ],
    left: [
      '................',
      '.....aaaaaa.....',
      '...aaAAAaaaab...',
      '..aaAAaaaaaabb..',
      '..aAaaaaaaaabb..',
      '..abbbbbaaaabb..',
      '..b.....aaaabb..',
      '........aaaabb..',
      '........aaaabb..',
      '........aaaabb..',
      '.......aaaabbb..',
      '......aaaabbbb..',
      '....aaaaaaabbb..',
    ],
  },
}
