/** Every term of art the game uses, in a sentence or two. Tap a dotted word to see one. */
export const GLOSSARY: Record<string, string> = {
  'cap rate': 'Net operating income divided by value. A 5% cap rate means paying $20 for every $1 of income. Lower cap rates mean higher prices.',
  'going-in cap': 'The income in place today divided by the price you pay.',
  'exit cap': 'The cap rate you assume a buyer will pay when you sell. Underwriting usually assumes it is wider than today\'s.',
  noi: 'Net operating income: rent and other revenue minus operating expenses, before debt service and capital spending.',
  occupancy: 'The share of the building that is leased. Market occupancy is what a building like this can realistically hold right now.',
  'loss-to-lease': 'How far the rents in place sit below market. It burns off as leases roll, which is free upside.',
  'market rent': 'What a vacant unit in this building would lease for today, given its quality and its market.',
  quality: 'The condition and competitiveness of the building, 0 to 100. Class A is 75+, class C under 45. It slips every year without capital.',
  ltv: 'Loan-to-value: the loan as a share of the property\'s value. More leverage raises returns when things go well and wipes out equity when they don\'t.',
  dscr: 'Debt service coverage ratio: NOI divided by interest. Fixed-rate lenders want at least 1.25x.',
  'debt yield': 'NOI divided by the loan. Bridge lenders size loans so stabilized income is at least 7.5% of the loan.',
  'bridge loan': 'Short-term floating-rate debt for buildings in transition: higher leverage, a rate that moves with the Fed, three years plus two one-year extensions, and almost no prepayment penalty.',
  'fixed-rate loan': 'Seven-year debt at a rate locked to the 10-year Treasury. Cheaper certainty, but lenders size it on today\'s income and charge yield maintenance to repay early.',
  'yield maintenance': 'The penalty for repaying a fixed-rate loan early: at least 1% of the balance, and much more if rates have fallen since you borrowed.',
  irr: 'Internal rate of return: the annual return that accounts for when each dollar went in and came out.',
  'levered irr': 'The IRR on your equity after the loan. Leverage magnifies it in both directions.',
  'equity multiple': 'Everything you got back divided by everything you put in. 2.0x doubles the money.',
  tvpi: 'Total value to paid-in: distributions plus remaining NAV, over capital called. The fund\'s multiple so far, net of fees and carry.',
  dpi: 'Distributions to paid-in: cash actually returned over capital called. LPs trust DPI more than marks.',
  'net irr': 'The IRR investors earn after the management fee and carried interest.',
  nav: 'Net asset value: what the fund\'s remaining buildings are worth after debt and accrued carry.',
  aum: 'Assets under management: the gross value of the buildings you run plus commitments not yet invested.',
  'dry powder': 'Committed capital a fund hasn\'t called yet, net of what business plans already need.',
  waterfall: 'The order a fund pays out: investors get their capital back, then the preferred return, then the GP catches up, then profits split 80/20.',
  'preferred return': 'The pref: the return LPs get before the GP earns any carry, usually 8% a year.',
  'catch-up': 'After the pref, the GP takes 100% of distributions until it has its full carry share of the profit so far.',
  carry: 'Carried interest: the GP\'s share of fund profits, usually 20%, paid only after LPs get their capital and pref.',
  'management fee': 'The annual fee on committed capital during the investment period, then on invested capital. It pays the firm\'s salaries.',
  'gp commitment': 'The firm\'s own money in each fund, 2% of commitments. It is called alongside the LPs\' money.',
  'j-curve': 'Funds look bad early: fees and costs go out before value comes back. The curve dips, then climbs.',
  'value-add': 'Renovating a tired building to raise its quality, rents and occupancy, then selling it stabilized.',
  repositioning: 'A heavy rebuild that lifts a building a full class. Expensive, slow, and a lot of the building goes offline while it happens.',
  'best and final': 'When bids are close, the broker asks every finalist for one last, highest offer.',
  're-trade': 'Asking the seller for a lower price after diligence finds problems. Sellers resent it; sometimes they agree.',
  diligence: 'Inspections, environmental reports, lease audits and title work before you close. It costs money and finds hidden problems.',
  'as-is': 'A sale with no diligence period and no promises. What you see is what you get, including what you can\'t see.',
  'credit line': 'When a fund\'s commitments are used up, a bank line covers shortfalls at a high rate, up to 15% of the fund. It is repaid before LPs see a dollar, and past the limit the bank forces sales.',
  'investment period': 'The first three years of a fund, when it can buy. After that it only manages and sells.',
  'fund term': 'Seven years from the first close. LPs can grant up to two one-year extensions.',
  fre: 'Fee-related earnings: management fees minus the cost of running the firm. GP-stakes buyers value firms on it.',
  'gp stake': 'A passive share of the firm\'s fees and carry, sold for cash to a specialist investor.',
  'off-market': 'A deal brought to you directly instead of shown to every buyer. Less competition, better pricing.',
}

export function lookup(term: string): string | undefined {
  return GLOSSARY[term.toLowerCase()]
}
