import type { WeaponDef, WeaponStats } from '../game/types'

/** One row of the DESIGN.md weapon table, in its column order. */
function stats(
  damage: number,
  cooldown: number,
  count: number,
  size: number,
  speed: number,
  duration: number,
  pierce: number,
  bounces: number,
  range: number,
  knockback: number,
  critChance = 0,
): WeaponStats {
  return { damage, cooldown, count, size, speed, duration, pierce, bounces, range, knockback, critChance }
}

/**
 * Every weapon in the game. Numbers follow DESIGN.md exactly; `behavior`
 * keys into `weapons/behaviors`, and `upgrades` holds the common-rarity step
 * for each stat a level-up may raise.
 */
export const WEAPONS: readonly WeaponDef[] = [
  {
    id: 'sword',
    name: 'Bonk Sword',
    icon: '⚔️',
    color: '#7fd8ff',
    description: 'A huge arc slash in front of you. Everything in it gets bonked.',
    behavior: 'sword',
    base: stats(16, 1.1, 1, 3.2, 0, 0.2, Infinity, 0, 4, 6),
    upgrades: { damage: 3, size: 0.3, critChance: 0.04, count: 1 },
  },
  {
    id: 'bone',
    name: 'Bone',
    icon: '🦴',
    color: '#f3ead2',
    description: 'A spinning bone that ricochets from skull to skull.',
    behavior: 'bone',
    base: stats(11, 1.0, 1, 0.5, 18, 3, 1, 3, 20, 3),
    upgrades: { damage: 2.5, bounces: 1, count: 1, speed: 2 },
  },
  {
    id: 'firestaff',
    name: 'Firestaff',
    icon: '🪄',
    color: '#ff7a1a',
    description: 'Fireballs that burst into flame and leave the crowd burning.',
    behavior: 'firestaff',
    base: stats(14, 1.4, 1, 2.5, 16, 3, 1, 0, 25, 4),
    upgrades: { damage: 3, size: 0.35, count: 1, cooldown: -0.08 },
  },
  {
    id: 'lightning',
    name: 'Storm Rod',
    icon: '⚡',
    color: '#7fe9ff',
    description: 'Calls lightning down on the nearest foe, then chains it onward.',
    behavior: 'lightning',
    base: stats(18, 1.6, 1, 1, 0, 0, 1, 3, 22, 1),
    upgrades: { damage: 4, bounces: 1, count: 1, cooldown: -0.1 },
  },
  {
    id: 'aura',
    name: 'Bonk Aura',
    icon: '💫',
    color: '#ff4fd8',
    description: 'A pulsing ring of pain that follows you everywhere.',
    behavior: 'aura',
    base: stats(6, 0.4, 1, 2.6, 0, 0, Infinity, 0, 0, 1),
    upgrades: { damage: 1.4, size: 0.35 },
  },
  {
    id: 'chunkers',
    name: 'Chunkers',
    icon: '🪨',
    color: '#a8927a',
    description: 'Boulders orbit you and flatten anything they touch.',
    behavior: 'chunkers',
    base: stats(12, 0.35, 2, 0.6, 2.4, 0, Infinity, 0, 2.8, 8),
    upgrades: { damage: 2.5, count: 1, size: 0.12, speed: 0.4 },
  },
  {
    id: 'bow',
    name: 'Longbow',
    icon: '🏹',
    color: '#8fdc5a',
    description: 'Fast arrows that punch straight through whole lines of enemies.',
    behavior: 'bow',
    base: stats(13, 0.9, 1, 0.4, 34, 1.2, 3, 0, 30, 2),
    upgrades: { damage: 3, pierce: 1, count: 1, critChance: 0.04 },
  },
  {
    id: 'revolver',
    name: 'Six-Shooter',
    icon: '🔫',
    color: '#ffd84a',
    description: 'Rapid tracer rounds that ricochet into the next target.',
    behavior: 'revolver',
    base: stats(9, 0.45, 1, 0.25, 40, 1, 1, 1, 26, 2),
    upgrades: { damage: 2, count: 1, bounces: 1, critChance: 0.05 },
  },
  {
    id: 'katana',
    name: 'Katana',
    icon: '🗡️',
    color: '#ff4d6d',
    description: 'Blink-fast slashes at whatever gets close. Loves to crit.',
    behavior: 'katana',
    base: stats(11, 0.55, 1, 2.4, 0, 0.15, Infinity, 0, 3.2, 3, 0.25),
    upgrades: { damage: 2.5, critChance: 0.05, count: 1, size: 0.2 },
  },
  {
    id: 'bananarang',
    name: 'Bananarang',
    icon: '🍌',
    color: '#ffe14a',
    description: 'A boomerang banana that bonks on the way out and on the way back.',
    behavior: 'bananarang',
    base: stats(13, 1.3, 1, 0.7, 20, 2, Infinity, 0, 14, 5),
    upgrades: { damage: 3, count: 1, size: 0.1, speed: 2 },
  },
  {
    id: 'frostwalker',
    name: 'Frostwalker',
    icon: '❄️',
    color: '#9ee7ff',
    description: 'Icy footprints chill whatever follows you, and a frost nova locks them solid.',
    behavior: 'frostwalker',
    base: stats(9, 2.5, 1, 1.4, 0, 3, Infinity, 0, 3, 0),
    upgrades: { damage: 2, duration: 0.5, size: 0.2 },
  },
  {
    id: 'flamewalker',
    name: 'Flamewalker',
    icon: '🔥',
    color: '#ff5a1f',
    description: 'Every step leaves a patch of fire. Keep moving, keep burning.',
    behavior: 'flamewalker',
    base: stats(7, 0.25, 1, 1.3, 0, 2.5, Infinity, 0, 0, 0),
    upgrades: { damage: 1.6, duration: 0.4, size: 0.15 },
  },
  {
    id: 'axe',
    name: 'Hurl Axe',
    icon: '🪓',
    color: '#ffa94d',
    description: 'Heavy axes lobbed high that tumble down through anything below.',
    behavior: 'axe',
    base: stats(22, 1.5, 1, 0.9, 14, 2, Infinity, 0, 12, 6),
    upgrades: { damage: 4, count: 1, size: 0.12, duration: 0.2 },
  },
  {
    id: 'mines',
    name: 'Pop Mines',
    icon: '💣',
    color: '#ff3b3b',
    description: 'Drops mines behind you that go off the moment something gets close.',
    behavior: 'mines',
    base: stats(26, 2.2, 1, 3, 0, 12, Infinity, 0, 1.2, 8),
    upgrades: { damage: 5, count: 1, size: 0.3, duration: 2 },
  },
  {
    id: 'tornado',
    name: 'Twister',
    icon: '🌪️',
    color: '#b8f3ff',
    description: 'Twisters that wander off, suck enemies in and grind them down.',
    behavior: 'tornado',
    base: stats(8, 3.0, 1, 1.6, 5, 4, Infinity, 0, 15, -4),
    upgrades: { damage: 1.6, count: 1, duration: 0.6, size: 0.2 },
  },
  {
    id: 'dagger',
    name: 'Homing Dagger',
    icon: '🔪',
    color: '#c77dff',
    description: 'Enchanted daggers that curve through the air and never miss.',
    behavior: 'dagger',
    base: stats(8, 0.8, 2, 0.3, 22, 2, 1, 0, 28, 1),
    upgrades: { damage: 1.8, count: 1, speed: 2, critChance: 0.03 },
  },
]

export const WEAPON_BY_ID: Readonly<Record<string, WeaponDef>> = Object.fromEntries(WEAPONS.map((w) => [w.id, w]))
